# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest



stages:

- stage: 'Development'
  jobs:
  - deployment: 'DeployToDevelopment'
    strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            - task: DockerCompose@0
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'azure-china-devops'
                azureContainerRegistry: '{"loginServer":"ffc0acr0ce20dev.azurecr.cn", "id" : "/subscriptions/2679f75f-10cb-466f-b2b4-ea24653a0e5c/resourceGroups/feature-flags-co-dev/providers/Microsoft.ContainerRegistry/registries/ffc0acr0ce20dev"}'
                dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
                action: 'Build services'
                includeLatestTag: true
                additionalImageTags: $(Build.BuildId)
                projectName: 'ffc-antd-demo'

            - task: DockerCompose@0
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'azure-china-devops'
                azureContainerRegistry: '{"loginServer":"ffc0acr0ce20dev.azurecr.cn", "id" : "/subscriptions/2679f75f-10cb-466f-b2b4-ea24653a0e5c/resourceGroups/feature-flags-co-dev/providers/Microsoft.ContainerRegistry/registries/ffc0acr0ce20dev"}'
                dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
                action: 'Push services'
                includeLatestTag: true
                additionalImageTags: $(Build.BuildId)
                projectName: 'ffc-antd-demo'

            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'azure-china-devops'
                appType: 'webAppContainer'
                WebAppName: 'ffc-webapp-antddemo-ce2-dev'
                DockerNamespace: 'ffc0acr0ce20dev.azurecr.cn'
                DockerRepository: 'ffc-antd-demo'
                DockerImageTag: '$(Build.BuildId)'

